[package]
name = "ntu-course-assistant"
version = "0.1.0"
description = "Local-first university timetable"
edition = "2021"

[lib]
name = "ntu_course_assistant_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
