import type { WorkplaceModule } from "./contracts.ts";

/** 编译期内置模块清单；不支持运行时安装或加载第三方代码。 */
export const BUILT_IN_MODULES = [
  {
    id: "workspace",
    metadata: { name: "工作台", description: "Links Workplace 首页与工作台外壳。" },
    order: 10,
    available: true,
    enabledByDefault: true,
    routes: [
      {
        id: "workspace.home",
        moduleId: "workspace",
        route: { area: "workspace", page: "home" },
        label: "工作台",
        order: 10,
        shellView: "workspace-home",
        available: true,
      },
    ],
    navigation: [
      {
        id: "workspace.mode",
        moduleId: "workspace",
        placement: "product-mode",
        label: "工作台",
        route: { area: "workspace", page: "home" },
        order: 10,
        available: true,
        productMode: "workspace",
      },
    ],
    settings: [
      {
        id: "workspace.home-settings",
        moduleId: "workspace",
        section: "工作台",
        pageId: "首页",
        label: "首页",
        order: 10,
        available: true,
      },
      {
        id: "workspace.timeline-settings",
        moduleId: "workspace",
        section: "工作台",
        pageId: "时间轴",
        label: "时间轴",
        order: 20,
        available: true,
      },
      {
        id: "workspace.quote-settings",
        moduleId: "workspace",
        section: "工作台",
        pageId: "每日寄语",
        label: "每日寄语",
        order: 30,
        available: true,
      },
    ],
    permissions: [
      {
        id: "workspace.read",
        moduleId: "workspace",
        action: "read",
        label: "工作台摘要",
        description: "允许 AI 读取当前工作台的时间与聚合状态。",
      },
    ],
    aiContextProviders: [
      {
        id: "workspace.ai-context",
        moduleId: "workspace",
        order: 10,
        permissionId: "workspace.read",
        sensitivity: "standard",
        priority: 10,
      },
    ],
  },
  {
    id: "academic",
    metadata: { name: "课表", description: "稳定的 Academic 课程与学业能力。" },
    order: 20,
    available: true,
    enabledByDefault: true,
    routes: [
      {
        id: "academic.schedule",
        moduleId: "academic",
        route: { area: "academic", page: "schedule" },
        label: "周课表",
        order: 10,
        shellView: "academic-schedule",
        available: true,
      },
      {
        id: "academic.changes",
        moduleId: "academic",
        route: { area: "academic", page: "changes" },
        label: "课程变化",
        order: 20,
        shellView: "academic-hub",
        available: true,
      },
      {
        id: "academic.tasks-legacy",
        moduleId: "academic",
        route: { area: "academic", page: "tasks-legacy" },
        label: "学业事项",
        order: 30,
        shellView: "academic-hub",
        available: true,
      },
      {
        id: "academic.exams",
        moduleId: "academic",
        route: { area: "academic", page: "exams" },
        label: "考试",
        order: 40,
        shellView: "academic-hub",
        available: true,
      },
      {
        id: "academic.semesters",
        moduleId: "academic",
        route: { area: "academic", page: "semesters" },
        label: "学期管理",
        order: 50,
        shellView: "academic-hub",
        available: true,
      },
    ],
    navigation: [
      {
        id: "academic.mode",
        moduleId: "academic",
        placement: "product-mode",
        label: "课表",
        route: { area: "academic", page: "schedule" },
        order: 20,
        available: true,
        productMode: "academic",
      },
      {
        id: "academic.schedule-nav",
        moduleId: "academic",
        placement: "academic-subnav",
        label: "周课表",
        route: { area: "academic", page: "schedule" },
        order: 10,
        available: true,
      },
      {
        id: "academic.changes-nav",
        moduleId: "academic",
        placement: "academic-subnav",
        label: "课程变化",
        route: { area: "academic", page: "changes" },
        order: 20,
        available: true,
      },
      {
        id: "academic.exams-nav",
        moduleId: "academic",
        placement: "academic-subnav",
        label: "考试",
        route: { area: "academic", page: "exams" },
        order: 30,
        available: true,
      },
      {
        id: "academic.semesters-nav",
        moduleId: "academic",
        placement: "academic-subnav",
        label: "学期管理",
        route: { area: "academic", page: "semesters" },
        order: 40,
        available: true,
      },
      {
        id: "academic.tasks-nav",
        moduleId: "academic",
        placement: "academic-subnav",
        label: "学业事项",
        route: { area: "academic", page: "tasks-legacy" },
        order: 50,
        available: true,
      },
    ],
    settings: [
      {
        id: "academic.periods-settings",
        moduleId: "academic",
        section: "课表",
        pageId: "作息",
        label: "作息",
        order: 10,
        available: true,
      },
      {
        id: "academic.display-settings",
        moduleId: "academic",
        section: "课表",
        pageId: "显示",
        label: "显示",
        order: 20,
        available: true,
      },
      {
        id: "academic.reminder-settings",
        moduleId: "academic",
        section: "课表",
        pageId: "提醒",
        label: "提醒",
        order: 30,
        available: true,
      },
      {
        id: "academic.widget-settings",
        moduleId: "academic",
        section: "课表",
        pageId: "Widget",
        label: "Widget",
        order: 40,
        available: true,
      },
      {
        id: "academic.import-settings",
        moduleId: "academic",
        section: "课表",
        pageId: "导入与数据",
        label: "导入与数据",
        order: 50,
        available: true,
      },
    ],
    searchProviders: [{ id: "academic.search", moduleId: "academic", order: 10 }],
    permissions: [
      {
        id: "academic.read",
        moduleId: "academic",
        action: "read",
        label: "课程与考试",
        description: "允许 AI 读取课程、考试与近期学业安排。",
      },
      {
        id: "academic.write",
        moduleId: "academic",
        action: "write",
        label: "修改课表",
        description: "通过 Academic 应用用例修改课程数据。",
      },
    ],
    aiContextProviders: [
      {
        id: "academic.ai-context",
        moduleId: "academic",
        order: 20,
        permissionId: "academic.read",
        sensitivity: "standard",
        priority: 20,
      },
    ],
  },
  {
    id: "planner",
    metadata: { name: "规划", description: "个人任务、日程、时间块与日常习惯。" },
    order: 30,
    available: true,
    enabledByDefault: true,
    routes: [
      {
        id: "planner.schedule",
        moduleId: "planner",
        route: { area: "workspace", page: "schedule" },
        label: "日程",
        order: 10,
        shellView: "workspace-schedule",
        available: true,
      },
      {
        id: "planner.tasks",
        moduleId: "planner",
        route: { area: "workspace", page: "tasks" },
        label: "任务",
        order: 20,
        shellView: "workspace-tasks",
        available: true,
      },
    ],
    searchProviders: [{ id: "planner.search", moduleId: "planner", order: 20 }],
    permissions: [
      {
        id: "planner.read",
        moduleId: "planner",
        action: "read",
        label: "计划与任务",
        description: "允许 AI 读取近期任务、日程事件与时间块。",
      },
      {
        id: "planner.write",
        moduleId: "planner",
        action: "write",
        label: "修改规划",
        description: "通过 Planner 应用用例修改个人规划。",
      },
      {
        id: "planner.propose",
        moduleId: "planner",
        action: "propose",
        label: "生成规划建议",
        description: "允许 AI 生成任务、日程或时间块提案；不直接写入，仍需用户确认。",
      },
    ],
    aiContextProviders: [
      {
        id: "planner.ai-context",
        moduleId: "planner",
        order: 30,
        permissionId: "planner.read",
        sensitivity: "standard",
        priority: 30,
      },
    ],
  },
  {
    id: "diary",
    metadata: { name: "日记", description: "本地优先的每日个人记录。" },
    order: 40,
    available: true,
    enabledByDefault: true,
    routes: [
      {
        id: "diary.page",
        moduleId: "diary",
        route: { area: "workspace", page: "diary" },
        label: "日记",
        order: 10,
        shellView: "workspace-diary",
        available: true,
      },
    ],
    searchProviders: [{ id: "diary.search", moduleId: "diary", order: 30 }],
    contextProviders: [{ id: "diary.context", moduleId: "diary", order: 10 }],
    permissions: [
      {
        id: "diary.read",
        moduleId: "diary",
        action: "read",
        label: "读取日记",
        description: "兼容旧权限标识；AI 不以此读取日记正文。正文需按条目单次授权。",
      },
      {
        id: "diary.write",
        moduleId: "diary",
        action: "write",
        label: "修改日记",
        description: "通过 Diary 应用用例修改本机日记。",
      },
      {
        id: "diary.body.read",
        moduleId: "diary",
        action: "body.read",
        label: "单次读取日记正文",
        description: "仅在用户对具体日记单次确认后读取正文。",
      },
    ],
    aiContextProviders: [
      {
        id: "diary.ai-context",
        moduleId: "diary",
        order: 60,
        permissionId: "diary.body.read",
        sensitivity: "sensitive",
        priority: 60,
      },
    ],
  },
  {
    id: "inbox",
    metadata: { name: "收件箱", description: "本机文本收集、解析预览与用户确认。" },
    order: 50,
    available: true,
    enabledByDefault: true,
    routes: [
      {
        id: "inbox.page",
        moduleId: "inbox",
        route: { area: "workspace", page: "inbox" },
        label: "收件箱",
        order: 10,
        shellView: "workspace-inbox",
        available: true,
      },
    ],
    searchProviders: [{ id: "inbox.search", moduleId: "inbox", order: 40 }],
    contextProviders: [{ id: "inbox.context", moduleId: "inbox", order: 20 }],
    permissions: [
      {
        id: "inbox.read",
        moduleId: "inbox",
        action: "read",
        label: "读取收件箱",
        description: "兼容旧权限标识；AI 不以此读取收件箱原文。原文需按条目单次授权。",
      },
      {
        id: "inbox.raw.read",
        moduleId: "inbox",
        action: "raw.read",
        label: "单次读取收件箱原文",
        description: "仅在用户对具体收件箱项目单次确认后读取原文。",
      },
    ],
    aiContextProviders: [
      {
        id: "inbox.ai-context",
        moduleId: "inbox",
        order: 70,
        permissionId: "inbox.raw.read",
        sensitivity: "sensitive",
        priority: 70,
      },
    ],
  },
  {
    id: "weather",
    metadata: { name: "天气", description: "用户主动选择地点的可选天气服务。" },
    order: 60,
    available: true,
    enabledByDefault: false,
    settings: [
      {
        id: "weather.settings",
        moduleId: "weather",
        section: "工作台",
        pageId: "天气",
        label: "天气",
        order: 40,
        available: true,
      },
    ],
    contextProviders: [{ id: "weather.context", moduleId: "weather", order: 30 }],
    permissions: [
      {
        id: "weather.read",
        moduleId: "weather",
        action: "read",
        label: "天气",
        description: "允许 AI 读取当前及当日近期天气摘要；不发送精确经纬度。",
      },
    ],
    aiContextProviders: [
      {
        id: "weather.ai-context",
        moduleId: "weather",
        order: 50,
        permissionId: "weather.read",
        sensitivity: "standard",
        priority: 50,
      },
    ],
  },
  {
    id: "routine",
    metadata: { name: "日常习惯", description: "只生成需用户确认的时间建议。" },
    order: 70,
    available: true,
    enabledByDefault: true,
    settings: [
      {
        id: "routine.settings",
        moduleId: "routine",
        section: "工作台",
        pageId: "日常习惯",
        label: "日常习惯",
        order: 50,
        available: true,
      },
    ],
    contextProviders: [{ id: "routine.context", moduleId: "routine", order: 40 }],
    permissions: [
      {
        id: "routine.read",
        moduleId: "routine",
        action: "read",
        label: "日常目标",
        description: "允许 AI 读取当日适用的习惯目标与当日状态。",
      },
    ],
    aiContextProviders: [
      {
        id: "routine.ai-context",
        moduleId: "routine",
        order: 40,
        permissionId: "routine.read",
        sensitivity: "standard",
        priority: 40,
      },
    ],
  },
  {
    id: "search",
    metadata: { name: "本机搜索", description: "通过内置模块 provider 执行本机统一搜索。" },
    order: 80,
    available: true,
    enabledByDefault: true,
    navigation: [
      {
        id: "search.header",
        moduleId: "search",
        placement: "header-action",
        label: "搜索",
        accessibilityLabel: "搜索本机内容",
        route: { area: "workspace", page: "search" },
        order: 10,
        available: true,
      },
    ],
    routes: [
      {
        id: "search.page",
        moduleId: "search",
        route: { area: "workspace", page: "search" },
        label: "搜索",
        order: 10,
        shellView: "workspace-search",
        available: true,
      },
    ],
  },
  {
    id: "settings",
    metadata: { name: "设置", description: "工作台、课表与通用偏好。" },
    order: 90,
    available: true,
    enabledByDefault: true,
    routes: [
      {
        id: "settings.main",
        moduleId: "settings",
        route: { area: "settings", page: "main" },
        label: "设置",
        order: 10,
        shellView: "unsupported",
        available: false,
      },
    ],
    settings: [
      {
        id: "settings.appearance",
        moduleId: "settings",
        section: "通用",
        pageId: "外观",
        label: "外观",
        order: 10,
        available: true,
      },
      {
        id: "settings.backup",
        moduleId: "settings",
        section: "通用",
        pageId: "数据与备份",
        label: "数据与备份",
        order: 20,
        available: true,
      },
      {
        id: "settings.privacy",
        moduleId: "settings",
        section: "通用",
        pageId: "隐私",
        label: "隐私",
        order: 30,
        available: true,
      },
      {
        id: "settings.about",
        moduleId: "settings",
        section: "通用",
        pageId: "关于",
        label: "关于",
        order: 40,
        available: true,
      },
      {
        id: "settings.ai-provider",
        moduleId: "settings",
        section: "工作台",
        pageId: "AI",
        label: "AI",
        order: 40,
        available: true,
      },
    ],
    navigation: [
      {
        id: "settings.header",
        moduleId: "settings",
        placement: "header-action",
        label: "设置",
        accessibilityLabel: "设置",
        route: { area: "settings", page: "main" },
        order: 20,
        available: true,
        action: "open-settings",
      },
    ],
  },
  {
    id: "ai",
    metadata: { name: "AI", description: "AI 运行能力尚未开放。" },
    order: 100,
    available: false,
    enabledByDefault: false,
    aiCapabilities: [
      {
        id: "ai.summary",
        moduleId: "ai",
        order: 10,
        name: "摘要",
        description: "仅基于本次明确提供且已授权的上下文生成摘要。",
        requiredPermissions: ["academic.read", "planner.read"],
      },
      {
        id: "ai.planning",
        moduleId: "ai",
        order: 20,
        name: "规划",
        description: "基于已授权的课表和规划上下文生成待审建议。",
        requiredPermissions: ["academic.read", "planner.read", "planner.propose"],
      },
      {
        id: "ai.suggestion",
        moduleId: "ai",
        order: 30,
        name: "建议",
        description: "生成不直接写入业务数据的规划提案。",
        requiredPermissions: ["planner.read", "planner.propose"],
      },
      {
        id: "ai.classification",
        moduleId: "ai",
        order: 40,
        name: "分类",
        description: "仅基于已授权的收件箱上下文提供分类建议。",
        requiredPermissions: ["inbox.raw.read"],
      },
    ],
    routes: [
      {
        id: "ai.page",
        moduleId: "ai",
        route: { area: "workspace", page: "ai" },
        label: "AI",
        order: 10,
        shellView: "unsupported",
        available: false,
      },
    ],
  },
] as const satisfies readonly WorkplaceModule[];
